var bd=D(1,function(a){var b=jc(0,a),a=b[0],b=M(1,[b[1]]);v([a,b])}),dd=J(function(){cd.b(bd)}),ed=J(function(){t(dd,function(a){L(1,[a.a[0],0,0])})}),hd=D(1,function(a){t(a,function(a){switch(h(a.a[0])>>>0&2095104|0){case 55296:u(gd);break;default:u(a)}})}),gd=K(1,function(){v(["\ufffd"])}),od=J(function(){id.d([hd,R],function(a){var b=D(1,function(b){var d=jc(8,b),b=d[0],d=M(1,[d[1]]);jd.d([d,nd,a,0,b],function(a){var b=a[0];t(a[1],function(a){var c=a.a[1];t(a.a[0],function(a){a=M(1,[a.a[0]]);a=
M(1,[a,c]);v([b,a])})})},[])});cd.d([b],function(a){var b=a.a[0];t(a.a[1],function(a){t(a.a[0],function(a){switch(a){case 0:u(ed);break;default:t(b,function(b){L(1,[b.a[0],0,a])})}})})},[])},[])}),pd=D(2,function(a,b){switch((10>a?n:o).c){case 1:var c=M(1,[i(48+a%10|0)]),c=M(2,[c,b]);pd.b(a/10|0,c);break;case 2:c=M(1,[i(48+a|0)]),L(2,[c,b])}}),qd=K(1,function(){v(["-"])}),rd=D(2,function(a,b){switch((0>a?n:o).c){case 1:pd.b(a,b);break;case 2:t(a,function(a){switch(a){case -2147483648:var d=J(function(){var a=
J(function(){pd.b(8,b)});pd.b(214748364,a)});L(2,[qd,d]);break;default:d=J(function(){pd.b(-a,b)}),L(2,[qd,d])}})}}),sd=K(1,function(){v(["("])}),td=K(1,function(){v([")"])}),nd=K(1,function(){v([4])}),ud=K(1,function(){v([])}),o=K(1,function(){v([])}),n=K(2,function(){v([])}),cd=D(1,function(a){a.d([0],function(a){u(a[1])},[])});D(1,function(a){vd.b(a)});
var vd=D(1,function(a){v([a,ud])}),id=D(2,function(a,b){t(b,function(b){switch(b.c){case 1:L(1,[]);break;case 2:var d=b.a[0],e=b.a[1],b=J(function(){id.b(a,e)}),f=J(function(){a.b(d)});L(2,[f,b])}})}),wd=D(2,function(){u(od)}),yd=D(2,function(a,b){xd.b(a,b)}),zd=G(function(){T.b("Data.Text.Array.new: size overflow\x00")}),Ad=D(1,function(a){t(a,function(a){u(a.a[0])})}),jd=D(5,function(a,b,c,d,e){var f=D(3,function(c,d,e){t(c,function(c){switch(c.c){case 1:var g=M(1,[d]),g=M(1,[a,g]);v([e,g]);break;
case 2:var s=c.a[1];t(c.a[0],function(g){var A=g.a[0];t(s,function(g){var r=h(A),s=J(function(){v(65536>r?n:o)}),Q=r-65536|0,H=D(2,function(e,k){t(b,function(b){var A=b.a[0];switch((e>=A?n:o).c){case 1:t(s,function(b){switch(b.c){case 1:t(a,function(a){var a=a.a[0],b=j(a,d,((Q>>10)+55296|0)>>>0&65535,k),a=j(a,d+1|0,((Q>>>0&1023|0)+56320|0)>>>0&65535,b);f.b(g,d+2|0,a)});break;case 2:t(a,function(a){a=j(a.a[0],d,r>>>0&65535,k);f.b(g,d+1|0,a)})}});break;case 2:var F=(A+1|0)<<1;switch((0>F?n:o).c){case 1:switch(F>>>
0&1073741824|0){case 0:var b=jc(F<<1,k),H=b[0],N=b[1];switch((0>=A?n:o).c){case 1:t(a,function(a){Cc(N,0,a.a[0],0,A>>>0);var a=M(1,[F]),b=M(1,[N]);jd.b(b,a,c,d,H)});break;case 2:var b=M(1,[F]),oa=M(1,[N]);jd.b(oa,b,c,d,H)}break;default:u(Bd)}break;case 2:u(Bd)}}})});t(s,function(a){switch(a.c){case 1:H.b(d+1|0,e);break;case 2:H.b(d,e)}})})})}})});f.b(c,d,e)}),Bd=G(function(){Cd.b(zd)}),U=K(1,function(){v([])}),Dd=D(1,function(a){u(a)}),Hd=D(1,function(a){Gd.b(a)}),Id=K(1,function(){v([9])}),Gd=x(1,
function(a){var b=J(function(){Jd.b(Id,a,R)});Kd.d(["Prelude.chr: bad argument: \x00",b],function(a){Cd.b(a)},[])}),Ld=D(2,function(a,b){t(b,function(b){switch(b.c){case 1:v([R,R]);break;case 2:var d=b.a[0],e=b.a[1];a.d([d],function(f){switch(f.c){case 1:v([R,b]);break;case 2:var g=J(function(){Ld.d([a,e],function(a){L(1,[a[0],a[1]])},[])}),f=J(function(){t(g,function(a){u(a.a[1])})}),l=J(function(){t(g,function(a){u(a.a[0])})}),l=M(2,[d,l]);v([l,f])}},[d,a,b,e])}})}),Md=D(3,function(a,b,c){switch((0>
b?n:o).c){case 1:rd.b(b,c);break;case 2:switch((6<a?n:o).c){case 1:rd.b(b,c);break;case 2:a=J(function(){var a=M(2,[td,c]);rd.b(b,a)}),L(2,[sd,a])}}}),Jd=D(3,function(a,b,c){t(a,function(a){var e=a.a[0];t(b,function(a){Md.b(e,a.a[0],c)})})}),Nd=D(2,function(a,b){t(a,function(a){switch(a){case 0:v(0);break;default:var d=sc(b,0);switch((0>a?n:o).c){case 1:v(d>>>0);break;case 2:v(-d>>>0)}}})}),Od=D(1,function(a){t(a,function(a){switch(a.c){case 1:v(a.a[0]>>>0);break;case 2:Nd.b(a.a[0],a.a[1])}})}),Pd=
D(1,function(a){L(1,[a])});

//@ sourceMappingURL=hs1min.js.map