var Xe=D(1,function(a){We.b(a,0)}),Ye=x(2,function(a,b){t(a,function(a){switch(a.c){case 1:L(1,[]);break;case 2:var d=a.a[0],e=a.a[1],f=a.a[3];switch((b>=a.a[2]?n:o).c){case 1:f=e+b|0;e=tc(d,f);switch((55296>e?n:o).c){case 1:switch((56319<e?n:o).c){case 1:d=tc(d,f+1|0);f=M(1,[b+2|0]);a=M(1,[a,f]);e=M(1,[i(((((e|0)-55296|0)<<10)+((d|0)-56320|0)|0)+65536|0)]);L(3,[e,a]);break;case 2:d=M(1,[b+1|0]),a=M(1,[a,d]),e=M(1,[i(e|0)]),L(3,[e,a])}break;case 2:d=M(1,[b+1|0]),a=M(1,[a,d]),e=M(1,[i(e|0)]),L(3,[e,
a])}break;case 2:Ye.b(f,0)}}})}),We=x(2,function(a,b){Ye.d([a,b],function(a){switch(a.c){case 1:L(1,[]);break;case 2:t(a.a[0],function(a){var b=a.a[0];t(a.a[1],function(a){We.b(b,a.a[0])})});break;case 3:var b=a.a[0];t(a.a[1],function(a){var c=a.a[0];t(a.a[1],function(a){var e=a.a[0],a=J(function(){We.b(c,e)});L(2,[b,a])})})}},[])}),$e=D(2,function(a,b){t(a,function(a){var d=J(function(){Ze.d([a,b],function(a){$e.b(a,b)},[b])});L(2,[a,d])})}),af=D(2,function(a,b){t(b,function(b){switch(b.c){case 1:L(2,
[]);break;case 2:var d=b.a[1];a.d([b.a[0]],function(b){switch(b.c){case 1:L(1,[]);break;case 2:af.b(a,d)}},[a,d])}})}),bf=D(2,function(a,b){t(b,function(b){switch(b.c){case 1:L(1,[]);break;case 2:var d=b.a[0],e=b.a[1];a.d([d],function(b){switch(b.c){case 1:L(1,[]);break;case 2:b=J(function(){bf.b(a,e)}),L(2,[d,b])}},[d,a,e])}})}),hf=D(2,function(a,b){var c=J(function(){var c=D(1,function(a){var c=J(function(){cf.b(a)});b.b(c)}),d=D(1,function(b){df.b(b,a,c)});ff.b(d)}),d=J(function(){gf.b(hf,b)}),
e=D(1,function(d){t(d,function(d){switch(d.c){case 3:t(d.a[0],function(e){switch(e.c){case 1:df.b(d,a,b);break;case 2:var f=e.a[1];t(e.a[0],function(e){t(e.a[0],function(e){switch(e){case "-":t(f,function(e){switch(e.c){case 1:u(c);break;case 2:df.b(d,a,b)}});break;default:df.b(d,a,b)}})})}});break;default:df.b(d,a,b)}})});ff.d([e],function(a){jf.b(a,d)},[d])}),lf=D(1,function(a){kf.b(0,a,R)}),mf=D(1,function(a){t(a,function(a){switch(a.c){case 1:L(1,[]);break;case 2:var c=a.a[1];t(a.a[0],function(a){var b=
a.a[0];t(a.a[1],function(a){switch(a.c){case 1:a=J(function(){mf.b(c)});L(2,[b,a]);break;case 2:mf.b(c)}})})}})}),of=J(function(){Cd.b(nf)}),qf=J(function(){Cd.b(pf)}),tf=D(1,function(a){var b=M(4,[a,rf]),c=D(1,function(){u(b)}),a=D(1,function(a){sf.b(a,c)});L(2,[a])}),nf=G(function(){T.b("Prelude.read: no parse\x00")}),pf=G(function(){T.b("Prelude.read: ambiguous parse\x00")}),uf=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:t(a.a[0],function(a){switch(a){case -2147483648:var c=Bc(-2147483648),
c=M(2,[c[0],c[1]]);uf.b(c,b);break;default:t(b,function(b){switch(b.c){case 1:var c=b.a[0],d=D(1,function(b){var d=D(1,function(){switch((0>a?n:o).c){case 1:var d=a/c|0,e=M(1,[b]),d=M(1,[d]);v([d,e]);break;case 2:switch((0<c?n:o).c){case 1:d=a/c|0;e=M(1,[b]);d=M(1,[d]);v([d,e]);break;case 2:d=(a+1|0)/c|0,e=M(1,[b]),d=M(1,[d-1|0]),v([d,e])}}});switch((0<a?n:o).c){case 1:d.b(0);break;case 2:switch((0>c?n:o).c){case 1:d.b(0);break;case 2:var e=(a-1|0)/c|0,d=M(1,[b]),e=M(1,[e-1|0]);v([e,d])}}}),e=a%c,
b=D(1,function(){switch((0>a?n:o).c){case 1:d.b(e);break;case 2:switch((0<c?n:o).c){case 1:d.b(e);break;case 2:t(e,function(a){switch(a){case 0:d.b(0);break;default:d.b(a+c|0)}})}}});switch((0<a?n:o).c){case 1:b.b(0);break;case 2:switch((0>c?n:o).c){case 1:b.b(0);break;case 2:t(e,function(a){switch(a){case 0:d.b(0);break;default:d.b(a+c|0)}})}}break;case 2:var g=Bc(a),g=M(2,[g[0],g[1]]);uf.b(g,b)}})}});break;case 2:var d=a.a[0],e=a.a[1];t(b,function(b){switch(b.c){case 1:b=Bc(b.a[0]);b=M(2,[b[0],
b[1]]);uf.b(a,b);break;case 2:var g,l=b.a[0];g=b.a[1];b=rc(d,e);l=rc(l,g);g=rb(b,l);var k=b.p(g.multiply(l));b.h()!==l.h()&&!k.m()&&(g=g.add(jb(-1)),k=k.add(l));g=qc(g).concat(qc(k));b=g[0];l=g[1];g=M(2,[g[2],g[3]]);b=M(2,[b,l]);v([b,g])}})}})}),vf=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:var d=a.a[0];t(b,function(a){switch(a.c){case 1:v(d!=a.a[0]?n:o);break;case 2:switch(Ac(a.a[0],a.a[1],d)){case 0:L(1,[]);break;default:L(2,[])}}});break;case 2:var e=a.a[0],f=a.a[1];t(b,function(a){switch(a.c){case 1:switch(Ac(e,
f,a.a[0])){case 0:L(1,[]);break;default:L(2,[])}break;case 2:switch(rc(e,f).o(rc(a.a[0],a.a[1]))){case 0:L(1,[]);break;default:L(2,[])}}})}})}),Nf=D(1,function(a){var b=J(function(){Xe.b(a)});wf.d([xf,b],function(a){mf.d([a],function(a){switch(a.c){case 1:u(of);break;case 2:var b=a.a[0];t(a.a[1],function(a){switch(a.c){case 1:yf.d([b,zf],function(a){switch(a.c){case 1:a=J(function(){lf.b(b)});a=M(2,[a]);a=M(5,[a]);a=M(6,[a,Af]);a=M(6,[Bf,a]);Cf.b(Df,a);break;case 2:a=D(1,function(a){Ef.d([a,a],function(a){Ff.b(a,
b)},[b])}),bf.d([a,Gf],function(a){var c=D(1,function(a){Hf.d([a,If],function(c){switch(c.c){case 1:uf.d([b,a],function(a){vf.b(a[1],Jf)},[]);break;case 2:u(Kf)}},[b,a])});af.d([c,a],function(a){switch(a.c){case 1:a=J(function(){lf.b(b)});a=M(2,[a]);a=M(5,[a]);a=M(6,[a,Af]);a=M(6,[Bf,a]);Cf.b(Df,a);break;case 2:a=J(function(){lf.b(b)}),a=M(2,[a]),a=M(5,[a]),a=M(6,[a,Lf]),a=M(6,[Mf,a]),Cf.b(Df,a)}},[b])},[b])}},[b]);break;case 2:u(qf)}})}},[])},[])}),Pf=G(function(){Of.b("<b>No</b>, \x00")}),Qf=K(3,
function(){v([Pf])}),Rf=K(5,function(){v([Qf])}),Bf=K(5,function(){v([Rf])}),Sf=G(function(){Of.b(" is not a prime</b>\x00")}),Tf=K(3,function(){v([Sf])}),Uf=K(5,function(){v([Tf])}),Af=K(5,function(){v([Uf])}),Vf=G(function(){Of.b("<b>Yes</b>, \x00")}),Wf=K(3,function(){v([Vf])}),Xf=K(5,function(){v([Wf])}),Mf=K(5,function(){v([Xf])}),Yf=G(function(){Of.b(" is a prime</b>\x00")}),Zf=K(3,function(){v([Yf])}),$f=K(5,function(){v([Zf])}),Lf=K(5,function(){v([$f])}),zf=K(1,function(){v([1])}),Jf=K(1,
function(){v([0])}),ag=K(1,function(){v([2])}),Gf=G(function(){$e.b(ag,zf)}),xf=G(function(){hf.b(bg,tf)});

//@ sourceMappingURL=hs3min.js.map