function cg(a,b){var c=a+b;return[c|0,c===(c|0)?0:1]}
var dg=K(1,function(){v([0])}),og=D(2,function(a,b){eg.d([a,fg],function(c){switch(c.c){case 1:gg.d([hg,a],function(a){switch(a.c){case 1:u(ig);break;case 2:var c=a.a[1];jg.d([a.a[0],fg],function(a){var d=a[1];kg.d([a[0]],function(a){switch((0<a?n:o).c){case 1:kg.d([d],function(a){var d=J(function(){lg.b(c,b)});mg.b(a,d)},[c,b]);break;case 2:var f=J(function(){kg.d([d],function(a){var d=J(function(){lg.b(c,b)});ng.b(9,a,d)},[c,b])});mg.b(a,f)}},[d,c,b])},[c,b])}},[b]);break;case 2:kg.d([a],function(a){mg.b(a,
b)},[b])}},[a,b])}),pg=D(2,function(a,b){eg.d([a,dg],function(c){switch(c.c){case 1:og.b(a,b);break;case 2:c=J(function(){cf.d([a],function(a){og.b(a,b)},[b])}),L(2,[qd,c])}},[a,b])}),kf=D(3,function(a,b,c){switch((6<a?n:o).c){case 1:pg.b(b,c);break;case 2:eg.d([b,dg],function(a){switch(a.c){case 1:pg.b(b,c);break;case 2:a=J(function(){var a=M(2,[td,c]);pg.b(b,a)}),L(2,[sd,a])}},[b,c])}}),fg=K(1,function(){v([1E9])}),qg=K(1,function(){v([465661287])}),rg=K(2,function(){v([qg,R])}),sg=K(1,function(){v([660865024])}),
tg=K(2,function(){v([sg,rg])}),hg=G(function(){ug.b(n,tg)}),vg=G(function(){T.b("jprinth []\x00")}),ig=G(function(){Cd.b(vg)}),wg=G(function(){T.b("jsplith: []\x00")}),xg=G(function(){Cd.b(wg)}),yg=x(2,function(a,b){t(b,function(b){switch(b.c){case 1:L(1,[]);break;case 2:var d=b.a[1];jg.d([b.a[0],a],function(b){var c=b[0],b=b[1],g=J(function(){yg.b(a,d)}),b=M(2,[b,g]);L(2,[c,b])},[a,d])}})}),gg=x(2,function(a,b){yf.d([a,b],function(c){switch(c.c){case 1:Ef.d([a,a],function(c){gg.d([c,b],function(b){switch(b.c){case 1:u(xg);
break;case 2:var c=b.a[1];jg.d([b.a[0],a],function(b){var d=b[0],e=b[1];yf.d([d,dg],function(b){switch(b.c){case 1:b=J(function(){yg.b(a,c)});L(2,[e,b]);break;case 2:b=J(function(){yg.b(a,c)}),b=M(2,[e,b]),L(2,[d,b])}},[a,d,e,c])},[a,c])}},[a])},[a,b]);break;case 2:L(2,[b,R])}},[a,b])}),mg=x(2,function(a,b){switch((10>a?n:o).c){case 1:var c=M(1,[i(48+a%10|0)]),c=M(2,[c,b]);mg.b(a/10|0,c);break;case 2:c=M(1,[i(48+a|0)]),L(2,[c,b])}}),ng=x(3,function(a,b,c){t(a,function(a){switch(a){case 1:a=M(1,[i(48+
b|0)]);L(2,[a,c]);break;default:var e=M(1,[i(48+b%10|0)]),e=M(2,[e,c]);ng.b(a-1|0,b/10|0,e)}})}),lg=x(2,function(a,b){t(a,function(a){switch(a.c){case 1:u(b);break;case 2:var d=a.a[1];jg.d([a.a[0],fg],function(a){var c=a[1];kg.d([a[0]],function(a){var e=J(function(){kg.d([c],function(a){var c=J(function(){lg.b(d,b)});ng.b(9,a,c)},[b,d])});ng.b(9,a,e)},[b,c,d])},[b,d])}})}),zg=D(2,function(a,b){t(a,function(a){switch(a){case 0:v(0);break;default:var d=sc(b,0);switch((0>a?n:o).c){case 1:u(d);break;
case 2:v(-d)}}})}),Ag=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:a=Bc(a.a[0]);a=M(2,[a[0],a[1]]);Ag.b(a,b);break;case 2:a=qc(rc(a.a[0],a.a[1]).shiftLeft(b)),L(2,[a[0],a[1]])}})}),Bg=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:var d=a.a[0];t(b,function(a){switch(a.c){case 1:L(1,[d>>>0|a.a[0]>>>0|0]);break;case 2:var b=Bc(d),b=M(2,[b[0],b[1]]);Bg.b(b,a)}});break;case 2:var e=a.a[0],f=a.a[1];t(b,function(b){switch(b.c){case 1:b=Bc(b.a[0]);b=M(2,[b[0],b[1]]);Bg.b(a,b);break;case 2:b=
qc(rc(e,f).C(rc(b.a[0],b.a[1]))),L(2,[b[0],b[1]])}})}})}),jg=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:t(a.a[0],function(a){switch(a){case -2147483648:var c=Bc(-2147483648),c=M(2,[c[0],c[1]]);jg.b(c,b);break;default:t(b,function(b){switch(b.c){case 1:var c=b.a[0],b=a/c|0,c=M(1,[a%c]),b=M(1,[b]);v([b,c]);break;case 2:c=Bc(a),c=M(2,[c[0],c[1]]),jg.b(c,b)}})}});break;case 2:var d=a.a[0],e=a.a[1];t(b,function(b){switch(b.c){case 1:b=Bc(b.a[0]);b=M(2,[b[0],b[1]]);jg.b(a,b);break;case 2:var g,
l=b.a[0];g=b.a[1];b=rc(d,e);g=rc(l,g);l=rb(b,g);b=b.p(l.multiply(g));g=qc(l).concat(qc(b));b=g[0];l=g[1];g=M(2,[g[2],g[3]]);b=M(2,[b,l]);v([b,g])}})}})}),eg=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:var d=a.a[0];t(b,function(a){switch(a.c){case 1:v(d<a.a[0]?n:o);break;case 2:a=Ac(a.a[0],a.a[1],d),v(0<a?n:o)}});break;case 2:var e=a.a[0],f=a.a[1];t(b,function(a){switch(a.c){case 1:a=Ac(e,f,a.a[0]);v(0>a?n:o);break;case 2:a=rc(e,f).o(rc(a.a[0],a.a[1])),v(0>a?n:o)}})}})}),yf=D(2,function(a,
b){t(a,function(a){switch(a.c){case 1:var d=a.a[0];t(b,function(a){switch(a.c){case 1:v(d>a.a[0]?n:o);break;case 2:a=Ac(a.a[0],a.a[1],d),v(0>a?n:o)}});break;case 2:var e=a.a[0],f=a.a[1];t(b,function(a){switch(a.c){case 1:a=Ac(e,f,a.a[0]);v(0<a?n:o);break;case 2:a=rc(e,f).o(rc(a.a[0],a.a[1])),v(0<a?n:o)}})}})}),Ef=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:var d=a.a[0];t(b,function(a){switch(a.c){case 1:var b=a.a[0],a=d*b;switch(a===(a|0)?0:1){case 0:L(1,[d*b|0]);break;default:var c=Bc(d),
a=c[0],c=c[1],b=Bc(b),b=M(2,[b[0],b[1]]),a=M(2,[a,c]);Ef.b(a,b)}break;case 2:b=Bc(d),b=M(2,[b[0],b[1]]),Ef.b(b,a)}});break;case 2:var e=a.a[0],f=a.a[1];t(b,function(b){switch(b.c){case 1:b=Bc(b.a[0]);b=M(2,[b[0],b[1]]);Ef.b(a,b);break;case 2:b=qc(rc(e,f).multiply(rc(b.a[0],b.a[1]))),L(2,[b[0],b[1]])}})}})}),Ze=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:var d=a.a[0];t(b,function(a){switch(a.c){case 1:var b=a.a[0],a=cg(d,b),c=a[0];t(a[1],function(a){switch(a){case 0:L(1,[c]);break;default:var e=
Bc(d),a=e[0],e=e[1],f=Bc(b),f=M(2,[f[0],f[1]]),a=M(2,[a,e]);Ze.b(a,f)}});break;case 2:var e=Bc(d),e=M(2,[e[0],e[1]]);Ze.b(e,a)}});break;case 2:var e=a.a[0],f=a.a[1];t(b,function(b){switch(b.c){case 1:b=Bc(b.a[0]);b=M(2,[b[0],b[1]]);Ze.b(a,b);break;case 2:b=qc(rc(e,f).add(rc(b.a[0],b.a[1]))),L(2,[b[0],b[1]])}})}})}),cf=D(1,function(a){t(a,function(a){switch(a.c){case 1:t(a.a[0],function(a){switch(a){case -2147483648:u(Cg);break;default:L(1,[-a])}});break;case 2:L(2,[-a.a[0],a.a[1]])}})}),kg=D(1,function(a){t(a,
function(a){switch(a.c){case 1:u(a.a[0]);break;case 2:zg.b(a.a[0],a.a[1])}})}),Eg=D(1,function(a){t(a,function(a){switch(a.c){case 1:u(Dg);break;case 2:var c=a.a[1];t(a.a[0],function(a){var b=a.a[0];Eg.d([c],function(a){Ag.d([a,31],function(a){var c=M(1,[b]);Bg.b(c,a)},[b])},[b])})}})}),ug=D(2,function(a,b){t(a,function(a){switch(a.c){case 1:Eg.d([b],function(a){cf.b(a)},[]);break;case 2:Eg.b(b)}})}),Dg=K(1,function(){v([0])}),Fg=K(1,function(){v([1])}),Gg=K(1,function(){v([2147483647])}),Cg=G(function(){Ze.b(Gg,
Fg)});

//@ sourceMappingURL=hs4min.js.map