function mf(a){this.value=a}
var nf=t(function(){y.b("ghc-prim")}),of=t(function(){y.b("GHC.Types")}),rf=q(2,function(a,c){var b=t(function(){a.d([pf],function(a){var b=a.a[0],d=a.a[1],n=a.a[2],p=a.a[3],r=t(function(){c.b(pf)}),a=t(function(){j(r,function(a){v(1,[a.a[0],a.a[1]])})}),a=x(2,[a,z]),b=x(1,[b,d]),b=x(2,[b,a]);qf.d([b],function(a){var b=a.a[0],a=a.a[1],c=t(function(){var a=x(2,[r,z]);D.b(p,a)});v(1,[b,a,n,c])},[r,n,p])},[c])}),d=q(1,function(){k(b)});k(d)}),sf=t(function(){y.b("GHC.Tuple")}),tf=t(function(){y.b("()")}),
uf=u(1,function(){m([Ra(2170319554,3688774321),Ra(26914641,3196943984),nf,sf,tf])}),vf=u(1,function(){m([Ra(2170319554,3688774321),Ra(26914641,3196943984),uf,z])}),wf=q(1,function(){k(vf)}),xf=t(function(){y.b("IO")}),yf=u(1,function(){m([Ra(1456544454,4198540223),Ra(3588501173,645407194),nf,of,xf])}),Cf=u(1,function(){m([Ra(1456544454,4198540223),Ra(3588501173,645407194),yf,z])}),Df=q(1,function(){k(Cf)}),Gf=t(function(){Ef.b(Ff)}),Nf=t(function(){Lf.b(Mf)}),Qf=q(4,function(a,c,b,d){var e=q(1,function(b){ud(Be,
[c,a,b],function(a){m([a,Of])})});Pf.b(e,b,d)}),Vf=q(3,function(a,c,b){var b=[b,0],d=b[0],b=b[1],e=q(2,function(b,d){j(b,function(b){var e=b.a[1],l=b.a[3];j(b.a[0],function(b){var n=b.a[0];j(e,function(b){var e=b.a[0];j(a,function(a){var b=a.a[0];switch((n<=b?g:i).c){case 1:k(Nf);break;case 2:switch((b<=e?g:i).c){case 1:k(Nf);break;case 2:var p=[d,l[b]],a=p[1],b=f(l,b,c,p[0]);m([b,a])}}})})})})});j(b,function(a){switch(a.toString()){case "0":a=q(1,function(a){j(Gf,function(b){var c=b.a[0];ud(Ae,[c,
a],function(a){var b=a[0],d=a[1],a=q(2,function(a,b){Qf.b(d,c,a,b)}),l=q(1,function(a){e.b(d,a)}),h=q(1,function(a){td(Fe,[l,a])});ud(Ce,[h,a,b],function(a){var b=a[1];ud(Be,[c,d,a[0]],function(a){m([a,b])})})})})});td(Ee,[a,d]);break;default:j(Gf,function(a){var b=a.a[0];ud(Ae,[b,d],function(a){var c=a[0],d=a[1],a=q(2,function(a,c){Qf.b(d,b,a,c)}),l=q(1,function(a){e.b(d,a)});ud(Ce,[l,a,c],function(a){var c=a[1];ud(Be,[b,d,a[0]],function(a){m([a,c])})})})})}})}),Wf=u(1,function(){m([0])}),Xf=u(1,
function(){m([64])}),Ff=o(1,function(a){var c=fc(65,E,a),b=[c[0],new ze],a=b[0],d=b[1],c=x(1,[Wf,Xf,65,c[1]]);ud(Be,[d,c,a],function(a){var a=[a,0],b=a[0],a=a[1],c=q(1,function(a){var b=x(1,[d]),c=[a,b],a=c[1],e=[c[0],a],c=e[0],e=e[1];switch(vc(a,e).c){case 1:hs_free_stable_ptr(a);m([c,e]);break;case 2:m([c,b])}});j(a,function(a){switch(a.toString()){case "0":td(Ee,[c,b]);break;default:c.b(b)}})})}),Mf=s(function(){y.b("GHC.Conc.setHandler: signal out of range")}),Yf=u(1,function(){m([0])}),bg=t(function(){Ef.b(Zf)}),
cg=o(3,function(a,c,b){j(a,function(a){var e=a.a[0];j(c,function(a){errorBelch2(e,a.a[0]);m([b,Of])})})}),dg=o(3,function(a,c,b){cg.b(a,c,b)}),gg=s(function(){eg.b(fg)}),hg=s(function(){y.b("no threads to run:  infinite loop or deadlock?")}),ig=s(function(){y.b("%s")}),jg=o(2,function(a,c){j(a,function(){m([c,Of])})}),tg=o(2,function(a,c){j(a,function(a){var d=a.a[0],e=a.a[1];ud(Ce,[gg,jg,c],function(a){kg.d([a[0]],function(a){var b=a[0],a=a[1],c=q(2,function(a,b){kg.d([b],function(b){var c=b[0],
b=b[1],l=q(2,function(b,c){dg.b(a,b,c)}),h=t(function(){lg.d([d],function(a){mg.d([a,pg,e],function(b){switch(b.c){case 1:mg.d([a,qg,e],function(a){switch(a.c){case 1:rg.d([d],function(a){gf.b(a,Yf,e,z)},[e]);break;case 2:j(a.a[0],function(a){k(a.a[0])})}},[d,e]);break;case 2:j(b.a[0],function(){k(hg)})}},[d,a,e])},[d,e])});sg.b(b,h,l,c)},[d,e,a])});sg.b(a,ig,c,b)},[d,e])})})}),Zf=o(1,function(a){var c=bc(tg,a),a=c[0],c=x(1,[c[1]]);m([a,c])}),rg=q(1,function(a){j(a,function(a){k(a.a[1])})}),ug=t(function(){y.b("stack overflow")}),
wg=q(1,function(a){D.b(ug,a)}),xg=t(function(){y.b("heap overflow")}),yg=q(1,function(a){D.b(xg,a)}),zg=t(function(){y.b("thread killed")}),Ag=q(1,function(a){D.b(zg,a)}),Bg=t(function(){y.b("user interrupt")}),Cg=q(1,function(a){D.b(Bg,a)}),Dg=q(2,function(a,c){j(c,function(a){switch(a.c){case 1:k(wg);break;case 2:k(yg);break;case 3:k(Ag);break;case 4:k(Cg)}})}),Lg=q(2,function(a,c){j(a,function(a){switch(a.c){case 1:Eg.b("[]",c);break;case 2:var d=a.a[0],e=a.a[1],a=t(function(){var a=t(function(){var a=
x(2,[Fg,c]),b=q(1,function(c){j(c,function(c){switch(c.c){case 1:k(a);break;case 2:var d=c.a[0],e=c.a[1],c=t(function(){j(d,function(a){switch(a.c){case 1:a=t(function(){b.b(e)});D.b(ug,a);break;case 2:a=t(function(){b.b(e)});D.b(xg,a);break;case 3:a=t(function(){b.b(e)});D.b(zg,a);break;case 4:a=t(function(){b.b(e)}),D.b(Bg,a)}})});v(2,[Ig,c])}})});b.b(e)});j(d,function(b){switch(b.c){case 1:D.b(ug,a);break;case 2:D.b(xg,a);break;case 3:D.b(zg,a);break;case 4:D.b(Bg,a)}})});v(2,[Kg,a])}})}),Mg=q(1,
function(a){j(a,function(a){switch(a.c){case 1:k(ug);break;case 2:k(xg);break;case 3:k(zg);break;case 4:k(Bg)}})}),Ng=u(1,function(){m([Dg,Mg,Lg])}),Og=t(function(){y.b("Deadlock")}),Rg=u(1,function(){m([Ra(51525854,1528534511),Ra(2498035378,3076107346),Pg,Qg,Og])}),Sg=u(1,function(){m([Ra(51525854,1528534511),Ra(2498035378,3076107346),Rg,z])}),pg=q(1,function(){k(Sg)}),Ug=q(1,function(a){j(a,function(a){var b=a.a[1];lg.d([a.a[0]],function(a){mg.b(a,Tg,b)},[b])})}),ch=u(1,function(){m([Tg,Ng,bh,Ug])}),
bh=q(1,function(a){v(1,[ch,a])}),dh=t(function(){y.b("ExitCode")}),eh=u(1,function(){m([Ra(1741995454,4203736966),Ra(3139257453,3149502275),Pg,Qg,dh])}),fh=u(1,function(){m([Ra(1741995454,4203736966),Ra(3139257453,3149502275),eh,z])}),gh=q(1,function(){k(fh)}),hh=u(4,function(){m([])}),ih=u(1,function(){m([2,0])}),jh=t(function(){y.b("hFlush")}),mh=q(2,function(a,c){kh.b(jh,a,lh,c)}),eg=q(2,function(a,c){mh.b(a,c)}),rh=t(function(){Ef.b(nh)}),Jh=s(function(){y.b("<stderr>")}),nh=o(1,function(a){j(Kh,
function(c){c.a[0].d([a],function(a){var c=a[0],a=x(2,[a[1]]);Lh.b(Mh,Nh,Oh,ih,Jh,Ph,i,a,Qh,Rh,E,c)},[])})}),lh=q(2,function(a,c){j(a,function(a){var d=a.a[1],e=a.a[3],l=a.a[5],a=[c,l.value],h=a[0];j(a[1],function(a){j(a.a[2],function(a){switch(a.c){case 1:m([h,Of]);break;case 2:var a=[h,l.value],b=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([d,e,a,b],function(a){a=cc(l,a[1],a[0]);m([a,Of])},[l]);break;case 2:m([b,Of])}})}})})})}),Th=t(function(){rf.b(Df,wf)}),Uh=u(1,function(){m([2])}),
Vh=q(1,function(a){mh.b(rh,a)}),Wh=q(2,function(a,c){j(a,function(){m([c,Of])})}),Xh=q(1,function(a){mh.b(fg,a)}),Yh=q(2,function(a,c){j(a,function(){m([c,Of])})}),$h=q(2,function(a,c){Zh.b(a,c)}),Zh=q(2,function(a,c){var b=q(1,function(b){ai.b(bi,a,b)});td(Ce,[b,$h,c])}),ci=t(function(){bh.b(hh)}),di=q(2,function(a,c){var b=q(1,function(b){var c=[b,Rd.t],b=c[0],c=x(1,[c[1]]),c=[b,new mf(c)],b=c[0],l=c[1],h=q(1,function(a){var a=[a,l.value===ea?0:1,l.value],b=a[0],c=a[2];j(a[1],function(a){switch(a.toString()){case "0":m([b,
Of]);break;default:j(c,function(a){a=$hs_killThreadzh(a.a[0],ci,b);m([a,Of])})}})}),c=t(function(){Th.b(h)}),c=x(1,[c,h]),n=q(2,function(a,b){h.b(b)}),c=x(1,[n,c]),c=x(2,[c]);Vf.d([Uh,c,b],function(b){a.b(b[0])},[a])});td(Ce,[b,$h,c])}),bi=o(2,function(a,c){j(a,function(a){shutdownHaskellAndExit(a.a[0]);m([c,Of])})}),ei=u(1,function(){m([1])}),fi=u(1,function(){m([0])}),gi=u(1,function(){m([2])}),ai=o(3,function(a,c,b){j(c,function(c){var e=c.a[0],l=c.a[1];ud(Ce,[Xh,Yh,b],function(b){ud(Ce,[Vh,Wh,
b[0]],function(b){var h=b[0];lg.d([e],function(b){var e=q(1,function(e){mg.d([b,gh,l],function(h){switch(h.c){case 1:mg.d([b,hi,l],function(b){switch(b.c){case 1:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])});break;case 2:j(b.a[0],function(b){var l=b.a[0],h=b.a[4];j(b.a[1],function(b){switch(b.c){case 18:j(h,function(b){switch(b.c){case 1:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])});break;case 2:var h=b.a[0];j(l,function(b){switch(b.c){case 1:j(bg,
function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])});break;case 2:var l=b.a[0];j(h,function(b){j(b.a[0],function(b){switch(b.toString()){case "-1":j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])});break;case "32":j(l,function(b){switch(b.c){case 1:var l=b.a[1];j(fg,function(b){switch(b.c){case 1:switch([ba,l===b.a[1]].c){case 1:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])});break;case 2:a.b(fi,e)}break;
case 2:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])})}});break;case 2:var h=b.a[1];j(fg,function(b){switch(b.c){case 1:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])});break;case 2:switch([ba,h===b.a[1]].c){case 1:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])});break;case 2:a.b(fi,e)}}})}});break;default:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])})}})})}})}});
break;default:j(bg,function(b){b=[e,b.a[0].value];b[1].d([c,b[0]],function(b){a.b(ei,b[0])},[a])})}})})}},[e,c,a]);break;case 2:j(h.a[0],function(b){switch(b.c){case 1:a.b(fi,e);break;case 2:a.b(b.a[0],e)}})}},[b,l,e,c,a])});mg.d([b,Tg,l],function(b){switch(b.c){case 1:e.b(h);break;case 2:j(b.a[0],function(b){switch(b.c){case 1:stackOverflow();a.b(gi,h);break;case 4:shutdownHaskellAndSignal(2);m([h,Of]);break;default:e.b(h)}})}},[b,l,c,a,e,h])},[l,c,a,h])})})})});q(1,function(a){di.b(hf,a)});

//@ sourceMappingURL=hs2min.js.map