function ii(a){a=Rc(a);a=Zc[a];return a===ba?ea:a}
var ji=q(1,function(a){j(a,function(a){k(a.a[3])})}),ki=q(1,function(a){j(a,function(a){k(a.a[3])})}),li=q(1,function(a){j(a,function(a){k(a.a[4])})}),mi=u(2,function(){m([])}),ri=q(8,function(a,c,b,d,e,l,h,n){j(h,function(h){var r=h.a[0],w=h.a[1],A=h.a[2],B=h.a[3],C=h.a[4],h=h.a[5],G=x(1,[a,c,b,d,0,0]),J=q(3,function(e,h,n){switch((h>=B?g:i).c){case 1:switch((e>=l?g:i).c){case 1:var p=Ac(a,e,n),n=p[0],p=Yb(p[1])>>>0&255,n=Jc(uc(r,h),0,p,n);J.b(e+1|0,h+1|0,n);break;case 2:h=x(1,[r,w,A,B,C,h]),p=t(function(){switch((e==
l?g:i).c){case 1:v(1,[a,c,b,d,e,l]);break;case 2:k(G)}}),h=x(1,[ni,p,h]),m([n,h])}break;case 2:h=x(1,[r,w,A,B,C,h]),p=t(function(){switch((e==l?g:i).c){case 1:v(1,[a,c,b,d,e,l]);break;case 2:k(G)}}),h=x(1,[qi,p,h]),m([n,h])}});J.b(e,h,n)})}),si=u(2,function(){m([])}),ti=u(1,function(){m([1,0])}),fg=t(function(){Ef.b(ui)}),wi=o(3,function(a,c,b){ud(Ae,[c,b],function(b){var e=b[0];j(b[1],function(b){var d=b.a[1],n=b.a[3],p=b.a[4],r=b.a[5],w=b.a[10],A=b.a[11],b=[e,r.value],B=b[0];j(b[1],function(b){var b=
b.a[2],e=q(1,function(b){j(p,function(d){switch(d.c){case 1:d=t(function(){vi.b(a)});ud(Be,[c,d,b],function(a){m([a,Of])});break;default:j(A,function(d){switch(d.c){case 1:j(w,function(d){switch(d.c){case 1:d=t(function(){vi.b(a)});ud(Be,[c,d,b],function(a){m([a,Of])});break;case 2:j(d.a[0],function(d){d.a[2].d([b],function(b){var b=b[0],d=t(function(){vi.b(a)});ud(Be,[c,d,b],function(a){m([a,Of])})},[c,a])})}});break;case 2:j(d.a[0],function(d){d.a[2].d([b],function(b){var d=b[0];j(w,function(b){switch(b.c){case 1:b=
t(function(){vi.b(a)});ud(Be,[c,b,d],function(a){m([a,Of])});break;case 2:j(b.a[0],function(b){b.a[2].d([d],function(b){var b=b[0],d=t(function(){vi.b(a)});ud(Be,[c,d,b],function(a){m([a,Of])})},[c,a])})}})},[c,w,a])})}})}})});j(b,function(b){switch(b.c){case 1:e.b(B);break;case 2:var b=[B,r.value],l=b[0];j(b[1],function(b){switch((b.a[4]==b.a[5]?g:i).c){case 1:Sh.d([d,n,b,l],function(a){a=cc(r,a[1],a[0]);e.b(a)},[c,r,p,A,w,a,e]);break;case 2:e.b(l)}})}})})})})}),xi=o(3,function(a,c,b){j(c,function(c){wi.b(a,
c.a[0],b)})}),Rh=u(2,function(){m([xi])}),yi=s(function(){y.b("<stdout>")}),ui=o(1,function(a){j(Kh,function(c){c.a[0].d([a],function(a){var c=a[0],a=x(2,[a[1]]);Lh.b(Mh,Nh,Oh,ti,yi,Ph,g,a,Qh,Rh,E,c)},[])})}),vi=q(1,function(a){a=x(2,[a]);a=x(1,[E,zi,z,Ai,E,a]);Bi.b(a,Ci)}),Di=q(8,function(a,c,b,d,e,l,h,n){j(a,function(a){var r=a.a[1],w=a.a[3],A=a.a[5],B=a.a[6],C=a.a[10],G=[n,A.value],J=G[0],H=G[1],N=q(3,function(b,c,d){j(c,function(c){var e=c.a[3],h=c.a[4],n=c.a[5],H=q(1,function(){Sh.d([r,w,c,d],
function(c){var d=cc(A,c[1],c[0]);j(b,function(b){var c=b.a[0],e=b.a[1],l=b.a[2],h=b.a[3],n=b.a[4],b=b.a[5];switch((n==b?g:i).c){case 1:Di.b(a,c,e,l,h,n,b,d);break;case 2:m([d,Of])}})},[A,b,a])});switch((e==n?g:i).c){case 1:j(b,function(b){var e=b.a[0],r=b.a[1],w=b.a[2],C=b.a[3],N=b.a[4],G=b.a[5],U=t(function(){m(N==G?g:i)}),J=q(1,function(){j(B,function(b){switch(b.c){case 1:H.b(0);break;case 2:var l=cc(A,c,d);j(U,function(b){switch(b.c){case 1:Di.b(a,e,r,w,C,N,G,l);break;case 2:m([l,Of])}});break;
case 3:j(b.a[0],function(b){switch(b.c){case 1:var l=cc(A,c,d);j(U,function(b){switch(b.c){case 1:Di.b(a,e,r,w,C,N,G,l);break;case 2:m([l,Of])}});break;case 2:j(b.a[0],function(b){switch(((n-h|0)>=b.a[0]?g:i).c){case 1:var l=cc(A,c,d);j(U,function(b){switch(b.c){case 1:Di.b(a,e,r,w,C,N,G,l);break;case 2:m([l,Of])}});break;case 2:H.b(0)}})}})}})});j(U,function(a){switch(a.c){case 1:switch((N==l?g:i).c){case 1:J.b(0);break;case 2:H.b(0)}break;case 2:J.b(0)}})});break;case 2:H.b(0)}})});j(C,function(n){switch(n.c){case 1:ri.d([c,
b,d,e,l,h,H,J],function(a){var b=a[0];j(a[1],function(a){N.b(a.a[1],a.a[2],b)})},[A,r,w,a,B,l,N]);break;case 2:j(n.a[0],function(n){var C=n.a[0],n=n.a[1],G=x(1,[c,b,d,e,l,h]);Ei.d([C,n,G,H,J],function(a){var b=a[0];j(a[1],function(a){N.b(a.a[0],a.a[1],b)})},[A,r,w,a,B,l,N])})}})})}),Fi=t(function(){y.b("cannot flush the read buffer: underlying device is not seekable")}),Gi=u(1,function(){m([E,zi,z,Fi,E,E])}),Ji=q(2,function(a,c){j(a,function(a){var d=a.a[0],e=a.a[3],l=a.a[5],a=[c,l.value],h=a[0];
j(a[1],function(a){var b=a.a[0],c=a.a[1],w=a.a[2],A=a.a[3],B=a.a[4],C=a.a[5];switch((B==C?g:i).c){case 1:ki.d([d,e,h],function(a){var h=a[0],a=a[1],n=q(1,function(a){var h=t(function(){Hi.b(-(C-B|0))});li.d([d,e,mi,h,a],function(a){var a=a[0],d=x(1,[b,c,w,A,0,0]),a=cc(l,d,a);m([a,Of])},[l,b,c,w,A])});j(a,function(a){switch(a.c){case 1:Ii.d([Gi,h],function(a){n.b(a[0])},[l,B,C,d,e,b,c,w,A,n]);break;case 2:n.b(h)}})},[l,B,C,d,e,b,c,w,A]);break;case 2:m([h,Of])}})})}),Pi=q(5,function(a,c,b,d,e){var l=
q(2,function(a,b){j(a,function(a){var c=a.a[1],e=a.a[3],l=a.a[5],h=a.a[7],C=a.a[8],G=a.a[11];j(a.a[4],function(J){switch(J.c){case 1:Ii.d([Ki,b],function(b){var c=b[0],b=x(1,[a,b[1]]);m([c,b])},[a]);break;case 2:Ii.d([Li,b],function(b){var c=b[0],b=x(1,[a,b[1]]);m([c,b])},[a]);break;case 3:Ii.d([Mi,b],function(b){var c=b[0],b=x(1,[a,b[1]]);m([c,b])},[a]);break;case 6:var J=[b,C.value],H=J[0];j(J[1],function(b){j(b.a[2],function(b){switch(b.c){case 1:var b=[H,C.value],n=b[0];j(b[1],function(b){var H=
b.a[2],N=b.a[4],J=b.a[5],U=q(1,function(b){Ji.d([a,b],function(b){var h=[b[0],C.value],b=h[0],n=h[1],h=t(function(){j(n,function(a){v(1,[a.a[0],a.a[1],Ni,a.a[3],a.a[4],a.a[5]])})}),b=[cc(C,h,b),l.value];ji.d([c,e,b[1],b[0]],function(b){b=cc(l,b[1],b[0]);d.d([a,b],function(b){var c=b[0],b=x(1,[a,b[1]]);m([c,b])},[a])},[a,d,l])},[a,d,C,l,c,e])});j(H,function(b){switch(b.c){case 1:switch((N==J?g:i).c){case 1:var b=[n,h.value],H=b[0];j(b[1],function(b){var h=b.a[0],n=b.a[1],B=[H,C.value],b=B[0],N=B[1],
B=t(function(){j(N,function(a){v(1,[a.a[0],a.a[1],a.a[2],a.a[3],0,0])})}),J=cc(C,B,b);j(N,function(b){var H=b.a[0],B=b.a[1],N=b.a[2];j(b.a[4],function(b){switch(b.toString()){case "0":var W=cc(l,n,J);U.b(W);break;default:j(G,function(G){switch(G.c){case 1:G=t(function(){j(n,function(a){v(1,[a.a[0],a.a[1],a.a[2],a.a[3],a.a[4]+b|0,a.a[5]])})});G=cc(l,G,J);U.b(G);break;case 2:j(G.a[0],function(G){var W=G.a[0],I=G.a[1];G.a[4].d([h,J],function(h){var h=h[0],G=x(1,[H,B,N,b,0,0]);Ei.d([W,I,n,G,h],function(a){var b=
a[0];j(a[1],function(a){a=cc(l,a.a[0],b);U.b(a)})},[a,d,C,l,c,e,U])},[a,d,C,l,c,e,U,n,b,W,I,H,B,N])})}})}})})});break;case 2:U.b(n)}break;case 2:U.b(n)}})});break;case 2:d.d([a,H],function(b){var c=b[0],b=x(1,[a,b[1]]);m([c,b])},[a])}})});break;default:d.d([a,b],function(b){var c=b[0],b=x(1,[a,b[1]]);m([c,b])},[a])}})})});Oi.b(a,c,b,l,e)}),kh=q(4,function(a,c,b,d){j(c,function(c){switch(c.c){case 1:var l=x(1,[c.a[1]]);Pi.b(a,c,l,b,d);break;case 2:l=x(1,[c.a[2]]),Pi.b(a,c,l,b,d)}})}),Qi=s(function(){y.b("handle is not open for writing")}),
Ai=s(function(){y.b("handle is finalized")}),Ki=u(1,function(){m([E,zi,z,Ri,E,E])}),Li=u(1,function(){m([E,zi,z,Ri,E,E])}),Mi=u(1,function(){m([E,zi,z,Qi,E,E])}),Si=t(function(){y.b("hPutChar")}),Ti=q(3,function(a,c,b){var d=q(2,function(a,b){j(a,function(a){var d=a.a[1],e=a.a[3],r=a.a[5],w=a.a[6],A=a.a[14],B=[b,a.a[8].value],C=B[0],G=B[1];j(c,function(b){switch(b.toString()){case "\n":var c=q(1,function(a){j(w,function(b){switch(b.c){case 2:var b=[a,r.value],c=b[0];j(b[1],function(a){switch((a.a[4]==
a.a[5]?g:i).c){case 1:Sh.d([d,e,a,c],function(a){a=cc(r,a[1],a[0]);m([a,Of])},[r]);break;case 2:m([c,Of])}});break;default:m([a,Of])}})});j(A,function(b){switch(b.c){case 1:j(G,function(b){var l=b.a[0],A=b.a[1],B=b.a[2],G=b.a[3],N=b.a[4],b=b.a[5],J=Ec(l,b,"\n",C);Di.d([a,l,A,B,G,N,b+1|0,J],function(a){c.b(a[0])},[w,r,d,e,c])});break;case 2:j(G,function(b){var l=b.a[0],A=b.a[1],B=b.a[2],G=b.a[3],N=b.a[4],J=b.a[5],b=Ec(l,J,"\r",C),J=J+1|0,b=Ec(l,J,"\n",b);Di.d([a,l,A,B,G,N,J+1|0,b],function(a){c.b(a[0])},
[w,r,d,e,c])})}});break;default:j(G,function(c){var d=c.a[0],e=c.a[1],l=c.a[2],n=c.a[3],r=c.a[4],c=c.a[5],p=Ec(d,c,b,C);Di.d([a,d,e,l,n,r,c+1|0,p],function(a){m([a[0],Of])},[])})}})})});kh.b(Si,a,d,b)}),Ui=q(3,function(a,c,b){j(c,function(c){switch(c.c){case 1:m([b,Of]);break;case 2:var e=c.a[1];j(c.a[0],function(c){Ti.d([a,c.a[0],b],function(b){Ui.b(a,e,b[0])},[a,e])})}})}),hj=q(9,function(a,c,b,d,e,l,h,n,p){var r=x(1,[e,l]),w=o(4,function(b,n,p,B){switch(((b+1|0)>=h?g:i).c){case 1:j(n,function(n){j(n.a[0],
function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){j(c,function(c){switch(c.c){case 1:var w=q(3,function(b,c,n){j(c,function(c){switch(c.c){case 1:var p=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,p,n);break;case 2:var p=
c.a[0],A=c.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(p,function(a){j(a.a[0],function(a){switch(a.toString()){case "\n":j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",n);w.b(b+1|0,A,a);break;case 2:var c=Ec(e,b,"\r",n),a=b+1|0,c=Ec(e,a,"\n",c);w.b(a+1|0,A,c)}});break;default:a=Ec(e,b,a,n),w.b(b+1|0,A,a)}})});break;case 2:p=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,p,n],function(a){w.b(0,c,a[0])},[e,l,r,h,a,w,d,
c])}}})});w.b(n,p,b);break;case 2:c=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],r=q(1,function(r){Di.d([a,e,l,Ni,h,0,n,r],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(r)})}),kh.d([Vi,a,c,b],function(b){var b=b[0],c=q(3,function(b,n,p){j(n,function(n){switch(n.c){case 1:var w=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],
n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,w,p);break;case 2:var w=n.a[0],A=n.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(w,function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){var p=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],r=q(1,function(r){Di.d([a,
e,l,Ni,h,0,n,r],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(r)})});kh.d([Vi,a,p,b],function(a){c.b(0,A,a[0])},[e,l,r,h,a,d,c,A])});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",p);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",p),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,p),c.b(b+1|0,A,n)}})});break;case 2:w=q(1,function(a){j(a,
function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,w,p],function(a){c.b(0,n,a[0])},[e,l,r,h,a,d,c,n])}}})});c.b(0,p,b)},[e,l,r,h,p,a,d])}})});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",B);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",B),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,B),A.b(b+1|0,p,n)}})});break;case 2:var C=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],
Of])},[])});k(c)})});kh.d([Vi,a,C,B],function(a){w.b(0,n,p,a[0])},[e,l,r,h,n,p,c,a,d,w])}}),A=q(3,function(b,n,p){j(n,function(n){switch(n.c){case 1:n=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,n,p);break;case 2:var H=n.a[0],B=n.a[1];
switch(((b+1|0)>=h?g:i).c){case 1:j(H,function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){j(c,function(c){switch(c.c){case 1:var p=q(3,function(b,c,n){j(c,function(c){switch(c.c){case 1:var w=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},
[r,h,c,d])});k(n)})});kh.b(Vi,a,w,n);break;case 2:var w=c.a[0],A=c.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(w,function(a){j(a.a[0],function(a){switch(a.toString()){case "\n":j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",n);p.b(b+1|0,A,a);break;case 2:var c=Ec(e,b,"\r",n),a=b+1|0,c=Ec(e,a,"\n",c);p.b(a+1|0,A,c)}});break;default:a=Ec(e,b,a,n),p.b(b+1|0,A,a)}})});break;case 2:w=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,
a,w,n],function(a){p.b(0,c,a[0])},[e,l,r,h,a,d,p,c])}}})});p.b(n,B,b);break;case 2:c=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],r=q(1,function(r){Di.d([a,e,l,Ni,h,0,n,r],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(r)})}),kh.d([Vi,a,c,b],function(b){var b=b[0],c=q(3,function(b,n,p){j(n,function(n){switch(n.c){case 1:var w=q(1,
function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,w,p);break;case 2:var w=n.a[0],A=n.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(w,function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){var p=q(1,function(a){j(a,function(a){var b=
a.a[1],c=a.a[3],d=a.a[5],r=q(1,function(r){Di.d([a,e,l,Ni,h,0,n,r],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(r)})});kh.d([Vi,a,p,b],function(a){c.b(0,A,a[0])},[e,l,r,h,a,d,c,A])});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",p);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",p),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,
p),c.b(b+1|0,A,n)}})});break;case 2:w=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,w,p],function(a){c.b(0,n,a[0])},[e,l,r,h,a,d,c,n])}}})});c.b(0,B,b)},[e,l,r,h,a,d,B])}})});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",p);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",p),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,p),A.b(b+1|0,B,n)}})});break;case 2:n=q(1,function(a){j(a,function(a){var c=q(1,
function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,n,p],function(a){w.b(0,H,B,a[0])},[e,l,r,h,c,a,d,w,H,B])}}})}),B=o(5,function(b,n,p,A,G){switch(((b+1|0)>=h?g:i).c){case 1:j(n,function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){j(c,function(c){switch(c.c){case 1:var w=q(4,function(b,c,n,p){j(c,function(c){switch(c.c){case 1:j(n,function(c){switch(c.c){case 1:c=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,
e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,c,p);break;case 2:w.b(b,c,z,p)}});break;case 2:var A=c.a[0],H=c.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(A,function(a){j(a.a[0],function(a){switch(a.toString()){case "\n":j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",p);w.b(b+1|0,H,n,a);break;case 2:var c=Ec(e,b,"\r",
p),a=b+1|0,c=Ec(e,a,"\n",c);w.b(a+1|0,H,n,c)}});break;default:a=Ec(e,b,a,p),w.b(b+1|0,H,n,a)}})});break;case 2:A=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,A,p],function(a){w.b(0,c,n,a[0])},[e,l,r,h,a,d,n,w,c])}}})});w.b(n,p,A,b);break;case 2:c=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],p=q(1,function(p){Di.d([a,e,l,Ni,h,0,n,p],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==
a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(p)})}),kh.d([Vi,a,c,b],function(b){var b=b[0],c=q(4,function(b,n,p,w){j(n,function(n){switch(n.c){case 1:j(p,function(d){switch(d.c){case 1:d=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],
c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,d,w);break;case 2:c.b(b,d,z,w)}});break;case 2:var A=n.a[0],H=n.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(A,function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var A=q(2,function(b,n){var w=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],p=q(1,function(p){Di.d([a,e,l,Ni,h,0,n,p],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=
cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(p)})});kh.d([Vi,a,w,b],function(a){c.b(0,H,p,a[0])},[e,l,r,h,a,d,p,c,H])});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",w);A.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",w),a=b+1|0,c=Ec(e,a,"\n",c);A.b(c,a+1|0)}});break;default:n=Ec(e,b,n,w),c.b(b+1|0,H,p,n)}})});break;case 2:A=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,A,w],function(a){c.b(0,
n,p,a[0])},[e,l,r,h,a,d,p,c,n])}}})});c.b(0,p,A,b)},[e,l,r,h,a,d,p,A])}})});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",G);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",G),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,G),C.b(b+1|0,p,A,n)}})});break;case 2:var I=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})});kh.d([Vi,a,I,G],function(a){B.b(0,n,p,A,a[0])},[e,l,r,h,c,a,d,w,n,p,A,B])}}),C=q(4,function(b,n,p,
A){j(n,function(n){switch(n.c){case 1:j(p,function(c){switch(c.c){case 1:c=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,c,A);break;case 2:w.b(b,c.a[0],c.a[1],A)}});break;case 2:var H=n.a[0],G=n.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(H,
function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){j(c,function(c){switch(c.c){case 1:var w=o(4,function(b,c,n,p){switch(((b+1|0)>=h?g:i).c){case 1:j(c,function(a){j(a.a[0],function(a){switch(a.toString()){case "\n":j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",p);A.b(b+1|0,n,a);break;case 2:var c=Ec(e,b,"\r",p),a=b+1|0,c=Ec(e,a,"\n",c);A.b(a+1|0,n,c)}});break;default:a=Ec(e,b,a,p),A.b(b+1|0,n,a)}})});break;case 2:var H=q(1,function(a){j(a,function(a){var c=
q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})});kh.d([Vi,a,H,p],function(a){w.b(0,c,n,a[0])},[e,l,r,h,a,d,c,n,w])}}),A=q(3,function(b,c,n){j(c,function(c){switch(c.c){case 1:c=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});
kh.b(Vi,a,c,n);break;case 2:var p=c.a[0],H=c.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(p,function(a){j(a.a[0],function(a){switch(a.toString()){case "\n":j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",n);A.b(b+1|0,H,a);break;case 2:var c=Ec(e,b,"\r",n),a=b+1|0,c=Ec(e,a,"\n",c);A.b(a+1|0,H,c)}});break;default:a=Ec(e,b,a,n),A.b(b+1|0,H,a)}})});break;case 2:c=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,c,n],function(a){w.b(0,
p,H,a[0])},[e,l,r,h,a,d,w,p,H])}}})}),H=o(5,function(b,c,n,p,A){switch(((b+1|0)>=h?g:i).c){case 1:j(c,function(a){j(a.a[0],function(a){switch(a.toString()){case "\n":j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",A);B.b(b+1|0,n,p,a);break;case 2:var c=Ec(e,b,"\r",A),a=b+1|0,c=Ec(e,a,"\n",c);B.b(a+1|0,n,p,c)}});break;default:a=Ec(e,b,a,A),B.b(b+1|0,n,p,a)}})});break;case 2:var C=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})});
kh.d([Vi,a,C,A],function(a){H.b(0,c,n,p,a[0])},[e,l,r,h,a,d,w,c,n,p,H])}}),B=q(4,function(b,c,n,p){j(c,function(c){switch(c.c){case 1:j(n,function(c){switch(c.c){case 1:c=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,c,p);break;case 2:w.b(b,
c.a[0],c.a[1],p)}});break;case 2:var A=c.a[0],C=c.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(A,function(a){j(a.a[0],function(a){switch(a.toString()){case "\n":j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",p);B.b(b+1|0,C,n,a);break;case 2:var c=Ec(e,b,"\r",p),a=b+1|0,c=Ec(e,a,"\n",c);B.b(a+1|0,C,n,c)}});break;default:a=Ec(e,b,a,p),B.b(b+1|0,C,n,a)}})});break;case 2:c=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,c,
p],function(a){H.b(0,A,C,n,a[0])},[e,l,r,h,a,d,w,H,n,A,C])}}})});B.b(n,G,p,b);break;case 2:c=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],p=q(1,function(p){Di.d([a,e,l,Ni,h,0,n,p],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(p)})}),kh.d([Vi,a,c,b],function(b){var b=b[0],c=o(4,function(b,p,w,A){switch(((b+1|0)>=h?g:i).c){case 1:j(p,
function(c){j(c.a[0],function(c){switch(c.toString()){case "\n":var p=q(2,function(b,c){var p=q(1,function(a){j(a,function(a){var b=a.a[1],d=a.a[3],n=a.a[5],p=q(1,function(p){Di.d([a,e,l,Ni,h,0,c,p],function(a){var a=[a[0],n.value],c=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,d,a,c],function(a){a=cc(n,a[1],a[0]);m([a,Of])},[n]);break;case 2:m([c,Of])}})},[n,b,d])});k(p)})});kh.d([Vi,a,p,b],function(a){n.b(0,w,a[0])},[e,l,r,h,a,d,n,w])});j(d,function(a){switch(a.c){case 1:a=
Ec(e,b,"\n",A);p.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",A),a=b+1|0,c=Ec(e,a,"\n",c);p.b(c,a+1|0)}});break;default:c=Ec(e,b,c,A),n.b(b+1|0,w,c)}})});break;case 2:var H=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})});kh.d([Vi,a,H,A],function(a){c.b(0,p,w,a[0])},[e,l,r,h,a,d,p,w,c])}}),n=q(3,function(b,p,w){j(p,function(p){switch(p.c){case 1:p=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,
Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,p,w);break;case 2:var A=p.a[0],H=p.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(A,function(c){j(c.a[0],function(c){switch(c.toString()){case "\n":var p=q(2,function(b,c){var p=q(1,function(a){j(a,function(a){var b=a.a[1],d=a.a[3],n=a.a[5],p=q(1,function(p){Di.d([a,e,l,Ni,h,0,c,p],
function(a){var a=[a[0],n.value],c=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,d,a,c],function(a){a=cc(n,a[1],a[0]);m([a,Of])},[n]);break;case 2:m([c,Of])}})},[n,b,d])});k(p)})});kh.d([Vi,a,p,b],function(a){n.b(0,H,a[0])},[e,l,r,h,a,d,n,H])});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",w);p.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",w),a=b+1|0,c=Ec(e,a,"\n",c);p.b(c,a+1|0)}});break;default:c=Ec(e,b,c,w),n.b(b+1|0,H,c)}})});break;case 2:p=q(1,function(a){j(a,function(a){var c=
q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,p,w],function(a){c.b(0,A,H,a[0])},[e,l,r,h,a,d,c,A,H])}}})}),w=o(5,function(b,n,p,H,B){switch(((b+1|0)>=h?g:i).c){case 1:j(n,function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){var w=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],p=q(1,function(p){Di.d([a,e,l,Ni,h,0,n,p],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,
c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(p)})});kh.d([Vi,a,w,b],function(a){A.b(0,p,H,a[0])},[e,l,r,h,a,d,c,A,p,H])});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",B);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",B),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,B),A.b(b+1|0,p,H,n)}})});break;case 2:var C=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})});kh.d([Vi,
a,C,B],function(a){w.b(0,n,p,H,a[0])},[e,l,r,h,a,d,c,n,p,H,w])}}),A=q(4,function(b,n,p,H){j(n,function(n){switch(n.c){case 1:j(p,function(d){switch(d.c){case 1:d=q(1,function(a){j(a,function(a){var c=a.a[8],d=a.a[9],n=q(1,function(n){Di.d([a,e,l,Ni,h,0,b,n],function(a){var a=[a[0],c.value],b=a[0];j(a[1],function(a){switch((h==a.a[3]?g:i).c){case 1:m([b,Of]);break;case 2:var c=[b,d.value],a=c[0],c=x(2,[r,c[1]]),a=cc(d,c,a);m([a,Of])}})},[r,h,c,d])});k(n)})});kh.b(Vi,a,d,H);break;case 2:c.b(b,d.a[0],
d.a[1],H)}});break;case 2:var B=n.a[0],C=n.a[1];switch(((b+1|0)>=h?g:i).c){case 1:j(B,function(n){j(n.a[0],function(n){switch(n.toString()){case "\n":var w=q(2,function(b,n){var w=q(1,function(a){j(a,function(a){var b=a.a[1],c=a.a[3],d=a.a[5],p=q(1,function(p){Di.d([a,e,l,Ni,h,0,n,p],function(a){var a=[a[0],d.value],e=a[0];j(a[1],function(a){switch((a.a[4]==a.a[5]?g:i).c){case 1:Sh.d([b,c,a,e],function(a){a=cc(d,a[1],a[0]);m([a,Of])},[d]);break;case 2:m([e,Of])}})},[d,b,c])});k(p)})});kh.d([Vi,a,
w,b],function(a){A.b(0,C,p,a[0])},[e,l,r,h,a,d,c,A,p,C])});j(d,function(a){switch(a.c){case 1:a=Ec(e,b,"\n",H);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",H),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,H),A.b(b+1|0,C,p,n)}})});break;case 2:n=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,n,H],function(a){w.b(0,B,C,p,a[0])},[e,l,r,h,a,d,c,w,p,B,C])}}})});A.b(0,G,p,b)},[e,l,r,h,a,d,p,G])}})});j(d,
function(a){switch(a.c){case 1:a=Ec(e,b,"\n",A);w.b(a,b+1|0);break;case 2:var c=Ec(e,b,"\r",A),a=b+1|0,c=Ec(e,a,"\n",c);w.b(c,a+1|0)}});break;default:n=Ec(e,b,n,A),C.b(b+1|0,G,p,n)}})});break;case 2:n=q(1,function(a){j(a,function(a){var c=q(1,function(c){Di.d([a,e,l,Ni,h,0,b,c],function(a){m([a[0],Of])},[])});k(c)})}),kh.d([Vi,a,n,A],function(a){B.b(0,H,G,p,a[0])},[e,l,r,h,c,a,d,w,B,p,H,G])}}})}),G=t(function(){j(b,function(a){switch(a.c){case 1:v(1,[]);break;case 2:k(Wi)}})});C.b(0,n,G,p)}),ij=t(function(){y.b("hPutStr")}),
kj=t(function(){Lf.b(jj)}),mj=u(1,function(){m([lj,kj])}),pj=q(2,function(a,c){j(a,function(a){var d=a.a[8],e=a.a[9],l=a.a[14];j(a.a[6],function(a){switch(a.c){case 1:var b=x(1,[mj,l]);m([c,b]);break;default:var b=[c,e.value],p=[b[0],d.value],r=p[0],w=p[1];j(b[1],function(b){switch(b.c){case 1:j(w,function(b){var c=b.a[3],b=Xb(c,4);switch((0>b?g:i).c){case 1:var d=bc(nj,r),e=d[1],d=jc(b,d[0]),b=d[0],d=d[1],e=x(1,[e]),e=x(2,[d,e]),c=x(1,[d,e,Ni,c,0,0]),c=x(1,[a,c]),c=x(1,[c,l]);m([b,c]);break;case 2:k(oj)}});
break;case 2:var c=b.a[0],b=cc(e,b.a[1],r),d=t(function(){j(c,function(a){var b=a.a[0],c=a.a[1];j(w,function(a){v(1,[b,c,Ni,a.a[3],0,0])})})}),d=x(1,[a,d]),d=x(1,[d,l]);m([b,d])}})}})})}),qj=q(4,function(a,c,b,d){kh.d([ij,a,pj,d],function(d){var l=d[0];j(d[1],function(d){var e=d.a[1];j(d.a[0],function(d){var h=d.a[1];j(d.a[0],function(d){switch(d.c){case 1:Ui.d([a,c,l],function(c){var d=c[0];j(b,function(b){switch(b.c){case 1:m([d,Of]);break;case 2:Ti.b(a,"\n",d)}})},[a,b]);break;case 2:j(h,function(d){hj.b(a,
g,b,e,d.a[0],d.a[1],d.a[3],c,l)});break;case 3:j(h,function(d){hj.b(a,i,b,e,d.a[0],d.a[1],d.a[3],c,l)})}})})})},[a,c,b])}),rj=q(3,function(a,c,b){qj.b(a,c,g,b)}),Vi=s(function(){y.b("commitBuffer")}),Wi=u(2,function(){m([sj,z])}),jj=s(function(){y.b("no buffer!")}),vj=q(2,function(a,c){var b=x(2,[a]),b=x(1,[E,si,tj,uj,E,b]);Ii.b(b,c)}),zj=q(2,function(a,c){j(wj,function(b){b.a[0].d([c],function(b){var c=b[0],b=b[1],l=q(2,function(b,c){j(b,function(b){var b=ii(b.a[0]),b=[c,b],d=b[0],e=b[1];switch(vc(e,
ea).c){case 1:j(xj,function(a){a.a[0].d([d],function(a){yj.b(a[1],e,a[0])},[e])});break;case 2:vj.b(a,d)}})});sg.b(b,a,l,c)},[a])})}),tj=s(function(){y.b("getEnv")}),uj=s(function(){y.b("no environment variable")}),Aj=q(2,function(a,c){rj.b(fg,a,c)}),hf=q(1,function(a){ud(Ce,[Bj,Cj,a],function(a){Aj.b(a[1],a[0])})}),Dj=t(function(){y.b("/Users/hamish/Library/Haskell/ghc-7.4.1.20120701/lib/fay-hello-js-0.1.0.0/bin")}),Ej=t(function(){y.b("fay_hello_js_bindir")}),Bj=q(1,function(a){zj.b(Ej,a)}),Cj=
q(2,function(a,c){j(a,function(a){var d=a.a[1];lg.d([a.a[0]],function(e){mg.d([e,hi,d],function(d){switch(d.c){case 1:m(De(a));break;case 2:m([c,Dj])}},[a,c])},[d,a,c])})});

//@ sourceMappingURL=hs3min.js.map